### ISSUE TITLE
Failed to open the referenced table 'arma3server'

### ISSUE THREAD

**Issue by iPrintScreen** [fugasjunior/arma-server-manager#103]
`2024-01-25 23:46:02,267 INFO o.h.v.i.u.Version HV000001: Hibernate Validator 8.0.1.Final
2024-01-25 23:46:02,326 INFO o.s.b.StartupInfoLogger Starting ServerManagerApplication v1.2.0 using Java 17.0.10 with PID 10352 (C:\Program Files\docker\arma-server-manager_v1.2.0\arma3-server-gui-1.2.0.jar started by Brokey in C:\Program Files\docker\arma-server-manager_v1.2.0)
2024-01-25 23:46:02,327 INFO o.s.b.SpringApplication No active profile set, falling back to 1 default profile: "default"
2024-01-25 23:46:03,340 INFO o.s.d.r.c.RepositoryConfigurationDelegate Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2024-01-25 23:46:03,456 INFO o.s.d.r.c.RepositoryConfigurationDelegate Finished Spring Data repository scanning in 104 ms. Found 6 JPA repository interfaces.
2024-01-25 23:46:04,405 INFO o.s.b.w.e.t.TomcatWebServer Tomcat initialized with port(s): 8080 (http)
2024-01-25 23:46:04,418 INFO o.a.j.l.DirectJDKLog Initializing ProtocolHandler ["http-nio-8080"]
2024-01-25 23:46:04,426 INFO o.a.j.l.DirectJDKLog Starting service [Tomcat]
2024-01-25 23:46:04,427 INFO o.a.j.l.DirectJDKLog Starting Servlet engine: [Apache Tomcat/10.1.13]
2024-01-25 23:46:04,548 INFO o.a.j.l.DirectJDKLog Initializing Spring embedded WebApplicationContext
2024-01-25 23:46:04,550 INFO o.s.b.w.s.c.ServletWebServerApplicationContext Root WebApplicationContext: initialization completed in 2166 ms
2024-01-25 23:46:04,855 INFO o.f.c.i.l.s.Slf4jLog Flyway Community Edition 9.6.0 by Redgate
2024-01-25 23:46:04,856 INFO o.f.c.i.l.s.Slf4jLog See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#9.6.0
2024-01-25 23:46:04,857 INFO o.f.c.i.l.s.Slf4jLog 
2024-01-25 23:46:04,880 INFO c.z.h.HikariDataSource HikariPool-1 - Starting...
2024-01-25 23:46:05,465 INFO c.z.h.p.HikariPool HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@47e4d9d0
2024-01-25 23:46:05,469 INFO c.z.h.HikariDataSource HikariPool-1 - Start completed.
2024-01-25 23:46:05,554 INFO o.f.c.i.l.s.Slf4jLog Database: jdbc:mysql://localhost:3306/mysql (MySQL 8.3)
2024-01-25 23:46:05,590 WARN o.f.c.i.l.s.Slf4jLog Flyway upgrade recommended: MySQL 8.3 is newer than this version of Flyway and support has not been tested. The latest supported version of MySQL is 8.0.
2024-01-25 23:46:05,680 INFO o.f.c.i.l.s.Slf4jLog Successfully validated 6 migrations (execution time 00:00.050s)
2024-01-25 23:46:05,725 INFO o.f.c.i.l.s.Slf4jLog Creating Schema History table `mysql`.`flyway_schema_history` with baseline ...
2024-01-25 23:46:05,880 INFO o.f.c.i.l.s.Slf4jLog Successfully baselined schema with version: 1
2024-01-25 23:46:05,908 INFO o.f.c.i.l.s.Slf4jLog Current version of schema `mysql`: 1
2024-01-25 23:46:05,924 INFO o.f.c.i.l.s.Slf4jLog Migrating schema `mysql` to version "1.1.0 - CREATE ARMA3 DIFFICULTY SETTINGS"
2024-01-25 23:46:05,962 ERROR o.f.c.i.l.s.Slf4jLog Migration of schema `mysql` to version "1.1.0 - CREATE ARMA3 DIFFICULTY SETTINGS" failed! Please restore backups and roll back database and code!
2024-01-25 23:46:05,983 WARN o.s.c.s.AbstractApplicationContext Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Migration V1_1_0__CREATE_ARMA3_DIFFICULTY_SETTINGS.sql failed
-------------------------------------------------------------
SQL State  : HY000
Error Code : 1824
Message    : Failed to open the referenced table 'arma3server'
Location   : db/migration/V1_1_0__CREATE_ARMA3_DIFFICULTY_SETTINGS.sql (C:\Program Files\docker\arma-server-manager_v1.2.0\file:\C:\Program Files\docker\arma-server-manager_v1.2.0\arma3-server-gui-1.2.0.jar!\BOOT-INF\classes!\db\migration\V1_1_0__CREATE_ARMA3_DIFFICULTY_SETTINGS.sql)
Line       : 31
Statement  : ALTER TABLE arma3difficulty_settings
    ADD CONSTRAINT FK_ARMA3DIFFICULTYSETTINGS_ON_SERVER FOREIGN KEY (server_id) REFERENCES arma3server (id)

2024-01-25 23:46:05,984 INFO c.z.h.HikariDataSource HikariPool-1 - Shutdown initiated...
2024-01-25 23:46:05,990 INFO c.z.h.HikariDataSource HikariPool-1 - Shutdown completed.
2024-01-25 23:46:05,993 INFO o.a.j.l.DirectJDKLog Stopping service [Tomcat]
2024-01-25 23:46:06,008 INFO o.s.b.a.l.ConditionEvaluationReportLogger 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-01-25 23:46:06,029 ERROR o.s.b.SpringApplication Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Migration V1_1_0__CREATE_ARMA3_DIFFICULTY_SETTINGS.sql failed
-------------------------------------------------------------
SQL State  : HY000
Error Code : 1824
Message    : Failed to open the referenced table 'arma3server'
Location   : db/migration/V1_1_0__CREATE_ARMA3_DIFFICULTY_SETTINGS.sql (C:\Program Files\docker\arma-server-manager_v1.2.0\file:\C:\Program Files\docker\arma-server-manager_v1.2.0\arma3-server-gui-1.2.0.jar!\BOOT-INF\classes!\db\migration\V1_1_0__CREATE_ARMA3_DIFFICULTY_SETTINGS.sql)
Line       : 31
Statement  : ALTER TABLE arma3difficulty_settings
    ADD CONSTRAINT FK_ARMA3DIFFICULTYSETTINGS_ON_SERVER FOREIGN KEY (server_id) REFERENCES arma3server (id)

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1158)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298)
	at cz.forgottenempire.servermanager.ServerManagerApplication.main(ServerManagerApplication.java:16)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Migration V1_1_0__CREATE_ARMA3_DIFFICULTY_SETTINGS.sql failed
-------------------------------------------------------------
SQL State  : HY000
Error Code : 1824
Message    : Failed to open the referenced table 'arma3server'
Location   : db/migration/V1_1_0__CREATE_ARMA3_DIFFICULTY_SETTINGS.sql (C:\Program Files\docker\arma-server-manager_v1.2.0\file:\C:\Program Files\docker\arma-server-manager_v1.2.0\arma3-server-gui-1.2.0.jar!\BOOT-INF\classes!\db\migration\V1_1_0__CREATE_ARMA3_DIFFICULTY_SETTINGS.sql)
Line       : 31
Statement  : ALTER TABLE arma3difficulty_settings
    ADD CONSTRAINT FK_ARMA3DIFFICULTYSETTINGS_ON_SERVER FOREIGN KEY (server_id) REFERENCES arma3server (id)

	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:384)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:274)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:273)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:246)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141)
	at org.flywaydb.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:58)
	at org.flywaydb.database.mysql.MySQLConnection.lock(MySQLConnection.java:152)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:143)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:98)
	at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:176)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:204)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:128)
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1817)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)
	... 26 common frames omitted
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: Migration V1_1_0__CREATE_ARMA3_DIFFICULTY_SETTINGS.sql failed
-------------------------------------------------------------
SQL State  : HY000
Error Code : 1824
Message    : Failed to open the referenced table 'arma3server'
Location   : db/migration/V1_1_0__CREATE_ARMA3_DIFFICULTY_SETTINGS.sql (C:\Program Files\docker\arma-server-manager_v1.2.0\file:\C:\Program Files\docker\arma-server-manager_v1.2.0\arma3-server-gui-1.2.0.jar!\BOOT-INF\classes!\db\migration\V1_1_0__CREATE_ARMA3_DIFFICULTY_SETTINGS.sql)
Line       : 31
Statement  : ALTER TABLE arma3difficulty_settings
    ADD CONSTRAINT FK_ARMA3DIFFICULTYSETTINGS_ON_SERVER FOREIGN KEY (server_id) REFERENCES arma3server (id)

	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:275)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:222)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:126)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:68)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.lambda$execute$0(SqlMigrationExecutor.java:57)
	at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:56)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:376)
	... 42 common frames omitted
Caused by: java.sql.SQLException: Failed to open the referenced table 'arma3server'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:763)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:201)
	at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:95)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:210)
	... 48 common frames omitted
`

**Comment by iPrintScreen** [comment]
`2024-01-26 00:02:38,974 INFO o.h.v.i.u.Version HV000001: Hibernate Validator 8.0.1.Final
2024-01-26 00:02:39,060 INFO o.s.b.StartupInfoLogger Starting ServerManagerApplication v1.2.0 using Java 17.0.10 with PID 11836 (C:\Program Files\docker\arma-server-manager_v1.2.0\arma3-server-gui-1.2.0.jar started by Brokey in C:\Program Files\docker\arma-server-manager_v1.2.0)
2024-01-26 00:02:39,061 INFO o.s.b.SpringApplication No active profile set, falling back to 1 default profile: "default"
2024-01-26 00:02:40,200 INFO o.s.d.r.c.RepositoryConfigurationDelegate Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2024-01-26 00:02:40,312 INFO o.s.d.r.c.RepositoryConfigurationDelegate Finished Spring Data repository scanning in 100 ms. Found 6 JPA repository interfaces.
2024-01-26 00:02:41,218 INFO o.s.b.w.e.t.TomcatWebServer Tomcat initialized with port(s): 8080 (http)
2024-01-26 00:02:41,231 INFO o.a.j.l.DirectJDKLog Initializing ProtocolHandler ["http-nio-8080"]
2024-01-26 00:02:41,235 INFO o.a.j.l.DirectJDKLog Starting service [Tomcat]
2024-01-26 00:02:41,236 INFO o.a.j.l.DirectJDKLog Starting Servlet engine: [Apache Tomcat/10.1.13]
2024-01-26 00:02:41,362 INFO o.a.j.l.DirectJDKLog Initializing Spring embedded WebApplicationContext
2024-01-26 00:02:41,365 INFO o.s.b.w.s.c.ServletWebServerApplicationContext Root WebApplicationContext: initialization completed in 2244 ms
2024-01-26 00:02:41,724 INFO o.f.c.i.l.s.Slf4jLog Flyway Community Edition 9.6.0 by Redgate
2024-01-26 00:02:41,725 INFO o.f.c.i.l.s.Slf4jLog See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#9.6.0
2024-01-26 00:02:41,725 INFO o.f.c.i.l.s.Slf4jLog 
2024-01-26 00:02:41,750 INFO c.z.h.HikariDataSource HikariPool-1 - Starting...
2024-01-26 00:02:42,241 INFO c.z.h.p.HikariPool HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@49798e84
2024-01-26 00:02:42,244 INFO c.z.h.HikariDataSource HikariPool-1 - Start completed.
2024-01-26 00:02:42,299 INFO o.f.c.i.l.s.Slf4jLog Database: jdbc:mysql://localhost:3306/mysql (MySQL 8.3)
2024-01-26 00:02:42,328 WARN o.f.c.i.l.s.Slf4jLog Flyway upgrade recommended: MySQL 8.3 is newer than this version of Flyway and support has not been tested. The latest supported version of MySQL is 8.0.
2024-01-26 00:02:42,450 WARN o.s.c.s.AbstractApplicationContext Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Validate failed: Migrations have failed validation
Detected failed migration to version 1.1.0 (CREATE ARMA3 DIFFICULTY SETTINGS).
Please remove any half-completed changes then run repair to fix the schema history.
Need more flexibility with validation rules? Learn more: https://rd.gt/3AbJUZE
2024-01-26 00:02:42,451 INFO c.z.h.HikariDataSource HikariPool-1 - Shutdown initiated...
2024-01-26 00:02:42,460 INFO c.z.h.HikariDataSource HikariPool-1 - Shutdown completed.
2024-01-26 00:02:42,467 INFO o.a.j.l.DirectJDKLog Stopping service [Tomcat]
2024-01-26 00:02:42,493 INFO o.s.b.a.l.ConditionEvaluationReportLogger 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-01-26 00:02:42,531 ERROR o.s.b.SpringApplication Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Validate failed: Migrations have failed validation
Detected failed migration to version 1.1.0 (CREATE ARMA3 DIFFICULTY SETTINGS).
Please remove any half-completed changes then run repair to fix the schema history.
Need more flexibility with validation rules? Learn more: https://rd.gt/3AbJUZE
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1158)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298)
	at cz.forgottenempire.servermanager.ServerManagerApplication.main(ServerManagerApplication.java:16)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
Detected failed migration to version 1.1.0 (CREATE ARMA3 DIFFICULTY SETTINGS).
Please remove any half-completed changes then run repair to fix the schema history.
Need more flexibility with validation rules? Learn more: https://rd.gt/3AbJUZE
	at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:134)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:204)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:128)
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1817)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)
	... 26 common frames omitted`
