### ISSUE TITLE
ARMA 3 fails to validate. "unidentified error"

### ISSUE THREAD

**Issue by Dav3y001** [fugasjunior/arma-server-manager#138]
after downloading arma 3 the sever goes through validation and gives the below error 
![image](https://github.com/user-attachments/assets/1d2fbac1-ceaf-4287-8979-3ca6a5e5c834)

the logs on the website do not have any indication of issues.

Below this is the docker logs i am unable to make any sense of this

`	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)

	at com.ibasco.agql.core.transport.handlers.MessageDecoder.exceptionCaught(MessageDecoder.java:93)

	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)

	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)

	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)

	at com.ibasco.agql.core.transport.handlers.ReadTimeoutHandler.readTimedOut(ReadTimeoutHandler.java:78)

	at com.ibasco.agql.core.transport.handlers.ReadTimeoutHandler.channelIdle(ReadTimeoutHandler.java:63)

	at io.netty.handler.timeout.IdleStateHandler$ReaderIdleTimeoutTask.run(IdleStateHandler.java:525)

	at io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:497)

	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)

	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)

	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)

	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)

	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)

	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:408)

	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)

	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)

	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

	at java.base/java.lang.Thread.run(Thread.java:840)

Caused by: com.ibasco.agql.core.exceptions.ReadTimeoutException: null

	at com.ibasco.agql.core.exceptions.ReadTimeoutException.<clinit>(ReadTimeoutException.java:27)

	... 16 common frames omitted`

**Comment by Colourpictures** [comment]
I have exactly the same problem.
Is there a fix or workaround yet?

DayZ and Reforger work fine.
Only any branch of Arma 3 becomes a problem.
