### ISSUE TITLE
[Issue] Could not Query Server

### ISSUE THREAD

**Issue by PatRakowicz** [fugasjunior/arma-server-manager#42]
Installed everyting and running through a docker container. Web interface worked and no problems.

When testing a server. Error code sends out
```
ERROR cz.forgottenempire.servermanager.serverinstance.CheckServerInstancesStatusCronJob: Couldn't query server TEST SERVER (ID 3) on port 3303
java.util.concurrent.ExecutionException: com.ibasco.agql.core.exceptions.ReadTimeoutException: Timeout occured for 'SessionId{id='SourceInfoResponse:127.0.0.1:3303'}' Started: 5.101000 seconds ago
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at cz.forgottenempire.servermanager.serverinstance.CheckServerInstancesStatusCronJob.updateServerInstanceInfo(CheckServerInstancesStatusCronJob.java:67)
	at cz.forgottenempire.servermanager.serverinstance.CheckServerInstancesStatusCronJob.lambda$checkServers$0(CheckServerInstancesStatusCronJob.java:41)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at cz.forgottenempire.servermanager.serverinstance.CheckServerInstancesStatusCronJob.checkServers(CheckServerInstancesStatusCronJob.java:36)
	at jdk.internal.reflect.GeneratedMethodAccessor114.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.ibasco.agql.core.exceptions.ReadTimeoutException: Timeout occured for 'SessionId{id='SourceInfoResponse:127.0.0.1:3303'}' Started: 5.101000 seconds ago
	at com.ibasco.agql.core.ReadRequestTimeoutTimerTask.run(ReadRequestTimeoutTimerTask.java:63)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	... 1 common frames omitted
```

**Comment by fugasjunior** [comment]
Hello,

this error sometimes happens when the Steam query times out before the server manages to start up fully. There is an automatic retry mechanism in place, though. If the error doesn't show up repeatedly and you get the server instance information in the GUI, the error can safely be ignored. 

However, I'll try to change it so this error message doesn't clutter the log files when it's not relevant.

**Comment by lividsubset3** [comment]
Wonderful, I couldn't test my server to the extent as it was like 4 am. 

But if this just a simple error that can be ignored I will do so forth.

Cheers.
