### ISSUE TITLE
Generated encryption keys sometimes don't work

### ISSUE THREAD

**Issue by fugasjunior** [fugasjunior/arma-server-manager#47]
Follow-up to https://github.com/fugasjunior/arma-server-manager/issues/45.

Sometimes the AES-256 keys generated by https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx don't work, causing the following exception.

```
org.springframework.orm.jpa.JpaSystemException: Error attempting to apply AttributeConverter; nested exception is javax.persistence.PersistenceException: Error attempting to apply AttributeConverter
...
Caused by: java.security.InvalidKeyException: No installed provider supports this key: javax.crypto.spec.SecretKeySpec
	at java.base/javax.crypto.Cipher.chooseProvider(Cipher.java:958)
	at java.base/javax.crypto.Cipher.init(Cipher.java:1299)
	at java.base/javax.crypto.Cipher.init(Cipher.java:1236)
	at cz.forgottenempire.servermanager.common.AttributeEncryptor.convertToDatabaseColumn(AttributeEncryptor.java:43)
	... 178 common frames omitted
```

Investigate this issue and find a reliable way of generating the encryption keys.

**Comment by fugasjunior** [comment]
This usually happens when the key contains `$` symbol and is loaded from the `.env` file. Workaround at this moment could be replacing it with another character.
