### ISSUE TITLE
set up instructions not intuitive!!!  

### ISSUE THREAD

**Issue by austrisD** [fugasjunior/arma-server-manager#58]
problems with set up need video or somethink

**Comment by fugasjunior** [comment]
Hi, what part of the setup are you having trouble with? Are you running on Windows or Linux? Do you want to run it in Docker or natively? If you need any help, let me know.

I'm not sure about creating a video guide - I think it would be really difficult to maintain and reflect all possible changes that may come in future versions. But I'm open to improving the instructions provided in the README file, if I know which parts of it are problematic.

**Comment by austrisD** [comment]
problems is with docker and database

**Comment by austrisD** [comment]
C:\arma\arma>java -jar arma3-server-gui.jar

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.7.5)

[30m2023-03-08 09:14:43,211[0;39m [34mINFO [0;39m [33morg.springframework.boot.StartupInfoLogger[0;39m: Starting ServerManagerApplication using Java 19.0.2 on ARMA3-common with PID 3296 (C:\arma\arma\arma3-server-gui.jar started by arma_gardums in C:\arma\arma)
[30m2023-03-08 09:14:43,211[0;39m [34mINFO [0;39m [33morg.hibernate.validator.internal.util.Version[0;39m: HV000001: Hibernate Validator 6.2.5.Final
[30m2023-03-08 09:14:43,216[0;39m [34mINFO [0;39m [33morg.springframework.boot.SpringApplication[0;39m: No active profile set, falling back to 1 default profile: "default"
[30m2023-03-08 09:14:44,502[0;39m [34mINFO [0;39m [33morg.springframework.data.repository.config.RepositoryConfigurationDelegate[0;39m: Bootstrapping Spring Data JPA repositories in DEFAULT mode.
[30m2023-03-08 09:14:44,595[0;39m [34mINFO [0;39m [33morg.springframework.data.repository.config.RepositoryConfigurationDelegate[0;39m: Finished Spring Data repository scanning in 96 ms. Found 6 JPA repository interfaces.
[30m2023-03-08 09:14:45,595[0;39m [34mINFO [0;39m [33morg.springframework.boot.web.embedded.tomcat.TomcatWebServer[0;39m: Tomcat initialized with port(s): 8080 (http)
[30m2023-03-08 09:14:45,611[0;39m [34mINFO [0;39m [33morg.apache.juli.logging.DirectJDKLog[0;39m: Initializing ProtocolHandler ["http-nio-8080"]
[30m2023-03-08 09:14:45,627[0;39m [34mINFO [0;39m [33morg.apache.juli.logging.DirectJDKLog[0;39m: Starting service [Tomcat]
[30m2023-03-08 09:14:45,627[0;39m [34mINFO [0;39m [33morg.apache.juli.logging.DirectJDKLog[0;39m: Starting Servlet engine: [Apache Tomcat/9.0.68]
[30m2023-03-08 09:14:45,720[0;39m [34mINFO [0;39m [33morg.apache.juli.logging.DirectJDKLog[0;39m: Initializing Spring embedded WebApplicationContext
[30m2023-03-08 09:14:45,720[0;39m [34mINFO [0;39m [33morg.springframework.boot.web.servlet.context.ServletWebServerApplicationContext[0;39m: Root WebApplicationContext: initialization completed in 2418 ms
[30m2023-03-08 09:14:46,002[0;39m [34mINFO [0;39m [33morg.flywaydb.core.internal.logging.slf4j.Slf4jLog[0;39m: Flyway Community Edition 9.6.0 by Redgate
[30m2023-03-08 09:14:46,002[0;39m [34mINFO [0;39m [33morg.flywaydb.core.internal.logging.slf4j.Slf4jLog[0;39m: See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#9.6.0
[30m2023-03-08 09:14:46,002[0;39m [34mINFO [0;39m [33morg.flywaydb.core.internal.logging.slf4j.Slf4jLog[0;39m:
[30m2023-03-08 09:14:46,017[0;39m [34mINFO [0;39m [33mcom.zaxxer.hikari.HikariDataSource[0;39m: HikariPool-1 - Starting...
[30m2023-03-08 09:14:46,299[0;39m [34mINFO [0;39m [33mcom.zaxxer.hikari.HikariDataSource[0;39m: HikariPool-1 - Start completed.
[30m2023-03-08 09:14:46,330[0;39m [34mINFO [0;39m [33morg.flywaydb.core.internal.logging.slf4j.Slf4jLog[0;39m: Database: jdbc:h2:mem:1db70dff-f027-47f8-a705-183887cf8ba8 (H2 2.1)
[30m2023-03-08 09:14:46,392[0;39m [34mINFO [0;39m [33morg.flywaydb.core.internal.logging.slf4j.Slf4jLog[0;39m: Successfully validated 2 migrations (execution time 00:00.017s)
[30m2023-03-08 09:14:46,408[0;39m [34mINFO [0;39m [33morg.flywaydb.core.internal.logging.slf4j.Slf4jLog[0;39m: Creating Schema History table "PUBLIC"."flyway_schema_history" ...
[30m2023-03-08 09:14:46,439[0;39m [34mINFO [0;39m [33morg.flywaydb.core.internal.logging.slf4j.Slf4jLog[0;39m: Current version of schema "PUBLIC": << Empty Schema >>
[30m2023-03-08 09:14:46,455[0;39m [34mINFO [0;39m [33morg.flywaydb.core.internal.logging.slf4j.Slf4jLog[0;39m: Migrating schema "PUBLIC" to version "1.0.0 - INIT SCHEMA"
[30m2023-03-08 09:14:46,470[0;39m [1;31mERROR[0;39m [33morg.flywaydb.core.internal.logging.slf4j.Slf4jLog[0;39m: Migration of schema "PUBLIC" to version "1.0.0 - INIT SCHEMA" failed! Please restore backups and roll back database and code!
[30m2023-03-08 09:14:46,486[0;39m [31mWARN [0;39m [33morg.springframework.context.support.AbstractApplicationContext[0;39m: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Migration V1_0_0__INIT_SCHEMA.sql failed
----------------------------------------
SQL State  : 42001
Error Code : 42001
Message    : Syntax error in SQL statement "CREATE TABLE arma3server\000d\000a(\000d\000a    id                   BIGINT   NOT NULL,\000d\000a    client_file_patching BIT[*](1)   NOT NULL,\000d\000a    server_file_patching BIT(1)   NOT NULL,\000d\000a    persistent           BIT(1)   NOT NULL,\000d\000a    battl_eye            BIT(1)   NOT NULL,\000d\000a    von_enabled          BIT(1)   NOT NULL,\000d\000a    verify_signatures    BIT(1)   NOT NULL,\000d\000a    additional_options   LONGTEXT NULL,\000d\000a    CONSTRAINT pk_arma3server PRIMARY KEY (id)\000d\000a)"; expected "ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
CREATE TABLE arma3server
(
    id                   BIGINT   NOT NULL,
    client_file_patching BIT(1)   NOT NULL,
    server_file_patching BIT(1)   NOT NULL,
    persistent           BIT(1)   NOT NULL,
    battl_eye            BIT(1)   NOT NULL,
    von_enabled          BIT(1)   NOT NULL,
    verify_signatures    BIT(1)   NOT NULL,
    additional_options   LONGTEXT NULL,
    CONSTRAINT pk_arma3server PRIMARY KEY (id)
) [42001-214]
Location   : db/migration/V1_0_0__INIT_SCHEMA.sql (C:\arma\arma\file:\C:\arma\arma\arma3-server-gui.jar!\BOOT-INF\classes!\db\migration\V1_0_0__INIT_SCHEMA.sql)
Line       : 11
Statement  : CREATE TABLE arma3server
(
    id                   BIGINT   NOT NULL,
    client_file_patching BIT(1)   NOT NULL,
    server_file_patching BIT(1)   NOT NULL,
    persistent           BIT(1)   NOT NULL,
    battl_eye            BIT(1)   NOT NULL,
    von_enabled          BIT(1)   NOT NULL,
    verify_signatures    BIT(1)   NOT NULL,
    additional_options   LONGTEXT NULL,
    CONSTRAINT pk_arma3server PRIMARY KEY (id)
)

[30m2023-03-08 09:14:46,486[0;39m [34mINFO [0;39m [33mcom.zaxxer.hikari.HikariDataSource[0;39m: HikariPool-1 - Shutdown initiated...
[30m2023-03-08 09:14:46,486[0;39m [34mINFO [0;39m [33mcom.zaxxer.hikari.HikariDataSource[0;39m: HikariPool-1 - Shutdown completed.
[30m2023-03-08 09:14:46,502[0;39m [34mINFO [0;39m [33morg.apache.juli.logging.DirectJDKLog[0;39m: Stopping service [Tomcat]
[30m2023-03-08 09:14:46,517[0;39m [34mINFO [0;39m [33morg.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener[0;39m:

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[30m2023-03-08 09:14:46,549[0;39m [1;31mERROR[0;39m [33morg.springframework.boot.SpringApplication[0;39m: Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Migration V1_0_0__INIT_SCHEMA.sql failed
----------------------------------------
SQL State  : 42001
Error Code : 42001
Message    : Syntax error in SQL statement "CREATE TABLE arma3server\000d\000a(\000d\000a    id                   BIGINT   NOT NULL,\000d\000a    client_file_patching BIT[*](1)   NOT NULL,\000d\000a    server_file_patching BIT(1)   NOT NULL,\000d\000a    persistent           BIT(1)   NOT NULL,\000d\000a    battl_eye            BIT(1)   NOT NULL,\000d\000a    von_enabled          BIT(1)   NOT NULL,\000d\000a    verify_signatures    BIT(1)   NOT NULL,\000d\000a    additional_options   LONGTEXT NULL,\000d\000a    CONSTRAINT pk_arma3server PRIMARY KEY (id)\000d\000a)"; expected "ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
CREATE TABLE arma3server
(
    id                   BIGINT   NOT NULL,
    client_file_patching BIT(1)   NOT NULL,
    server_file_patching BIT(1)   NOT NULL,
    persistent           BIT(1)   NOT NULL,
    battl_eye            BIT(1)   NOT NULL,
    von_enabled          BIT(1)   NOT NULL,
    verify_signatures    BIT(1)   NOT NULL,
    additional_options   LONGTEXT NULL,
    CONSTRAINT pk_arma3server PRIMARY KEY (id)
) [42001-214]
Location   : db/migration/V1_0_0__INIT_SCHEMA.sql (C:\arma\arma\file:\C:\arma\arma\arma3-server-gui.jar!\BOOT-INF\classes!\db\migration\V1_0_0__INIT_SCHEMA.sql)
Line       : 11
Statement  : CREATE TABLE arma3server
(
    id                   BIGINT   NOT NULL,
    client_file_patching BIT(1)   NOT NULL,
    server_file_patching BIT(1)   NOT NULL,
    persistent           BIT(1)   NOT NULL,
    battl_eye            BIT(1)   NOT NULL,
    von_enabled          BIT(1)   NOT NULL,
    verify_signatures    BIT(1)   NOT NULL,
    additional_options   LONGTEXT NULL,
    CONSTRAINT pk_arma3server PRIMARY KEY (id)
)

        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
        at cz.forgottenempire.servermanager.ServerManagerApplication.main(ServerManagerApplication.java:14)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Migration V1_0_0__INIT_SCHEMA.sql failed
----------------------------------------
SQL State  : 42001
Error Code : 42001
Message    : Syntax error in SQL statement "CREATE TABLE arma3server\000d\000a(\000d\000a    id                   BIGINT   NOT NULL,\000d\000a    client_file_patching BIT[*](1)   NOT NULL,\000d\000a    server_file_patching BIT(1)   NOT NULL,\000d\000a    persistent           BIT(1)   NOT NULL,\000d\000a    battl_eye            BIT(1)   NOT NULL,\000d\000a    von_enabled          BIT(1)   NOT NULL,\000d\000a    verify_signatures    BIT(1)   NOT NULL,\000d\000a    additional_options   LONGTEXT NULL,\000d\000a    CONSTRAINT pk_arma3server PRIMARY KEY (id)\000d\000a)"; expected "ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
CREATE TABLE arma3server
(
    id                   BIGINT   NOT NULL,
    client_file_patching BIT(1)   NOT NULL,
    server_file_patching BIT(1)   NOT NULL,
    persistent           BIT(1)   NOT NULL,
    battl_eye            BIT(1)   NOT NULL,
    von_enabled          BIT(1)   NOT NULL,
    verify_signatures    BIT(1)   NOT NULL,
    additional_options   LONGTEXT NULL,
    CONSTRAINT pk_arma3server PRIMARY KEY (id)
) [42001-214]
Location   : db/migration/V1_0_0__INIT_SCHEMA.sql (C:\arma\arma\file:\C:\arma\arma\arma3-server-gui.jar!\BOOT-INF\classes!\db\migration\V1_0_0__INIT_SCHEMA.sql)
Line       : 11
Statement  : CREATE TABLE arma3server
(
    id                   BIGINT   NOT NULL,
    client_file_patching BIT(1)   NOT NULL,
    server_file_patching BIT(1)   NOT NULL,
    persistent           BIT(1)   NOT NULL,
    battl_eye            BIT(1)   NOT NULL,
    von_enabled          BIT(1)   NOT NULL,
    verify_signatures    BIT(1)   NOT NULL,
    additional_options   LONGTEXT NULL,
    CONSTRAINT pk_arma3server PRIMARY KEY (id)
)

        at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:384)
        at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:274)
        at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
        at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:273)
        at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:246)
        at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141)
        at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate$1.call(TableLockingExecutionTemplate.java:36)
        at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
        at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate.execute(TableLockingExecutionTemplate.java:31)
        at org.flywaydb.core.internal.database.base.Connection.lock(Connection.java:102)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:143)
        at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:98)
        at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:176)
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:204)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:128)
        at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
        ... 24 common frames omitted
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: Migration V1_0_0__INIT_SCHEMA.sql failed
----------------------------------------
SQL State  : 42001
Error Code : 42001
Message    : Syntax error in SQL statement "CREATE TABLE arma3server\000d\000a(\000d\000a    id                   BIGINT   NOT NULL,\000d\000a    client_file_patching BIT[*](1)   NOT NULL,\000d\000a    server_file_patching BIT(1)   NOT NULL,\000d\000a    persistent           BIT(1)   NOT NULL,\000d\000a    battl_eye            BIT(1)   NOT NULL,\000d\000a    von_enabled          BIT(1)   NOT NULL,\000d\000a    verify_signatures    BIT(1)   NOT NULL,\000d\000a    additional_options   LONGTEXT NULL,\000d\000a    CONSTRAINT pk_arma3server PRIMARY KEY (id)\000d\000a)"; expected "ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
CREATE TABLE arma3server
(
    id                   BIGINT   NOT NULL,
    client_file_patching BIT(1)   NOT NULL,
    server_file_patching BIT(1)   NOT NULL,
    persistent           BIT(1)   NOT NULL,
    battl_eye            BIT(1)   NOT NULL,
    von_enabled          BIT(1)   NOT NULL,
    verify_signatures    BIT(1)   NOT NULL,
    additional_options   LONGTEXT NULL,
    CONSTRAINT pk_arma3server PRIMARY KEY (id)
) [42001-214]
Location   : db/migration/V1_0_0__INIT_SCHEMA.sql (C:\arma\arma\file:\C:\arma\arma\arma3-server-gui.jar!\BOOT-INF\classes!\db\migration\V1_0_0__INIT_SCHEMA.sql)
Line       : 11
Statement  : CREATE TABLE arma3server
(
    id                   BIGINT   NOT NULL,
    client_file_patching BIT(1)   NOT NULL,
    server_file_patching BIT(1)   NOT NULL,
    persistent           BIT(1)   NOT NULL,
    battl_eye            BIT(1)   NOT NULL,
    von_enabled          BIT(1)   NOT NULL,
    verify_signatures    BIT(1)   NOT NULL,
    additional_options   LONGTEXT NULL,
    CONSTRAINT pk_arma3server PRIMARY KEY (id)
)

        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:275)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:222)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:126)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:68)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.lambda$execute$0(SqlMigrationExecutor.java:57)
        at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:56)
        at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:376)
        ... 42 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE arma3server\000d\000a(\000d\000a    id                   BIGINT   NOT NULL,\000d\000a    client_file_patching BIT[*](1)   NOT NULL,\000d\000a    server_file_patching BIT(1)   NOT NULL,\000d\000a    persistent           BIT(1)   NOT NULL,\000d\000a    battl_eye            BIT(1)   NOT NULL,\000d\000a    von_enabled          BIT(1)   NOT NULL,\000d\000a    verify_signatures    BIT(1)   NOT NULL,\000d\000a    additional_options   LONGTEXT NULL,\000d\000a    CONSTRAINT pk_arma3server PRIMARY KEY (id)\000d\000a)"; expected "ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
CREATE TABLE arma3server
(
    id                   BIGINT   NOT NULL,
    client_file_patching BIT(1)   NOT NULL,
    server_file_patching BIT(1)   NOT NULL,
    persistent           BIT(1)   NOT NULL,
    battl_eye            BIT(1)   NOT NULL,
    von_enabled          BIT(1)   NOT NULL,
    verify_signatures    BIT(1)   NOT NULL,
    additional_options   LONGTEXT NULL,
    CONSTRAINT pk_arma3server PRIMARY KEY (id)
) [42001-214]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
        at org.h2.message.DbException.getSyntaxError(DbException.java:261)
        at org.h2.command.Parser.getSyntaxError(Parser.java:900)
        at org.h2.command.Parser.read(Parser.java:5675)
        at org.h2.command.Parser.readIfMore(Parser.java:1268)
        at org.h2.command.Parser.parseCreateTable(Parser.java:9272)
        at org.h2.command.Parser.parseCreate(Parser.java:6784)
        at org.h2.command.Parser.parsePrepared(Parser.java:763)
        at org.h2.command.Parser.parse(Parser.java:689)
        at org.h2.command.Parser.parse(Parser.java:666)
        at org.h2.command.Parser.prepareCommand(Parser.java:569)
        at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
        at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:237)
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
        at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
        at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:201)
        at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:95)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:210)
        ... 48 common frames omitted

C:\arma\arma>

**Comment by fugasjunior** [comment]
Thanks for providing the log. It seems that you're trying to use the H2 in-memory database instead of the MySQL database provided in the `docker-compose.yml` file which is also preconfigured in the `.env.EXAMPLE` file. Was this your intention?

The application only supports MySQL. Using other database type is not trivial as it would require code changes. I'd recommend using the provided `docker-compose.yml`, keeping the default database settings in `.env` file (except passwords, change those) and executing command `docker compose up`. This should automatically setup the correct database and connect it with the application.

Let me know if you need more help with the setup.

**Comment by Weilbyte** [comment]
I was able to get it working with H2 by making it run in MySQL compatibility mode using the `MODE=MySQL` parameters, like so:
```
spring.datasource.url=jdbc:h2:file:C:/arma3-gui/config/database;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
```
